// [FAST TRACK] Add asset here to enable transferring from one network to another
export const tokensPerChannel = [
	{
		networks: ['BIFROST_KUSAMA', 'PICASSO'],
		tokens: ['BNC_KSM', 'vKSM'],
	},
	{
		networks: ['BIFROST_POLKADOT', 'COMPOSABLE'],
		tokens: ['BNC_DOT', 'vDOT'],
	},
	{
		networks: ['ASTAR', 'COMPOSABLE'],
		tokens: ['ASTR'],
	},
	{
		networks: ['SHIDEN', 'PICASSO'],
		tokens: ['SDN'],
	},
	{
		networks: ['PICASSO', 'COMPOSABLE'],
		tokens: ['DOT', 'PICA', 'vDOT', 'BNC_DOT', 'ASTR', 'lsDOT', 'BLD', 'IST'],
	},
	{
		networks: ['PICASSO', 'STATEMINE'],
		tokens: ['USDT Kusama'],
	},
	{
		networks: ['PICASSO', 'TINKERNET'],
		tokens: ['TNKR'],
	},

	{
		networks: ['PICASSO', 'AMPLITUDE'],
		tokens: ['AMPE', 'XLM'],
	},
	{
		networks: ['CENTAURI', 'COREUM'],
		tokens: ['COREUM', 'XRP'],
	},
	{
		networks: ['CENTAURI', 'ARCHWAY'],
		tokens: ['ARCH'],
	},
	{
		networks: ['PICASSO', 'MOONRIVER'],
		tokens: ['MOVR', 'PICA'],
	},
	{
		networks: ['PICASSO', 'KUSAMA'],
		tokens: ['KSM'],
	},
	{
		networks: ['PICASSO', 'CENTAURI'],
		tokens: ['PICA', 'KSM', 'DOT', 'UMEE', 'ASTR', 'SDN', 'USDT Kusama'],
	},
	{
		networks: ['CENTAURI', 'ETHEREUM'],
		tokens: [
			'PICA',
			'ETH',
			'DAI',
			'FXS',
			'sFRAX',
			'sfrxETH',
			'OSMO',
			'ENA',
			'FRAX',
			'frxETH',
			'wBTC',
			'pxETH',
			'PEPE',
			'CRV',
			'rETH',
			'crvUSD',
			'eETH',
			'USDe',
			'USDT Ethereum',
			'stETH',
			'ATOM',
			// 'STARS',
			'IST',
			'stATOM',
			'BLD',
			// 'ezETH',
			'SEI',
			'SCRT',
			'STRD',
			// 'DOT',
			// 'KSM',
			// 'SILK',
		],
	},
	{
		networks: ['CENTAURI', 'CHIHUAHUA'],
		tokens: ['UHUAHUA'],
	},
	{
		networks: ['CENTAURI', 'OSMOSIS'],
		tokens: ['UOSMO', 'USEI' /*, 'milkTIA'*/],
	},
	{
		networks: ['CENTAURI', 'COSMOS'],
		tokens: ['ATOM'],
	},
	{
		networks: ['CENTAURI', 'STRIDE'],
		tokens: ['STRD', 'stATOM' /*, 'stTIA'*/],
	},
	{
		networks: ['CENTAURI', 'STARGAZE'],
		tokens: ['STARS'],
	},
	{
		networks: ['CENTAURI', 'CRESCENT'],
		tokens: ['CRE', 'BCRE', 'UCRE'],
	},
	{
		networks: ['CENTAURI', 'SECRET'],
		tokens: ['SCRT', 'SILK', 'SHD'],
	},
	{
		networks: ['CENTAURI', 'NEUTRON'],
		tokens: ['NTRN'],
	},
	{
		networks: ['CENTAURI', 'UMEE'],
		tokens: ['UMEE'],
	},
	{
		networks: ['CENTAURI', 'AGORIC'],
		tokens: ['BLD', 'IST'],
	},
	{
		networks: ['CENTAURI', 'SEI'],
		tokens: ['SEI'],
	},
	{
		networks: ['CENTAURI', 'CELESTIA'],
		tokens: ['TIA'],
	},
	{
		networks: ['CENTAURI', 'KUJIRA'],
		tokens: ['KUJI'],
	},
	{
		networks: ['CENTAURI', 'QUICKSILVER'],
		tokens: ['QCK'],
	},
	{
		networks: ['CENTAURI', 'INJECTIVE'],
		tokens: ['INJ'],
	},
	{
		networks: ['COMPOSABLE', 'POLKADOT'],
		tokens: ['DOT'],
	},
	{
		networks: ['COMPOSABLE', 'MOONBEAM'],
		tokens: ['GLMR', 'PICA', 'TIA', 'IST', 'BLD', 'ATOM'],
	},
	{
		networks: ['OSMOSIS', 'SEI'],
		tokens: ['UOSMO', 'USEI'],
	},
	{
		networks: ['CENTAURI', 'SOLANA'],
		tokens: [
			'PICA',
			'OSMO',
			'SOL',
			'ETH',
			'wSOL',
			'WHINE',
			'LST',
			'bSOL',
			'JitoSOL',
			'edgeSOL',
			'hSOL',
			'jupSOL',
			'mSOL',
			'BONK',
			'WIF',
			'USDT Solana',
			//ethereum
			'DAI',
			'USDT Ethereum',
			'CRV',
			'wBTC',
			'rETH',
			'crvUSD',
			'FRAX',
			'FXS',
			'frxETH',
			'sfrxETH',
			'sFRAX',
			'pxETH',
			'eETH',
			'ENA',
			'USDe',
			'PEPE',
			//cosmos
			'ATOM',
			'stATOM',
			'IST',
			'SEI',
			'SCRT',
			'STARS',
			'BLD',
			'STRD',
			'SHD',
			'SILK',
			'DOT',
			'KSM',
			'XRP',
			'COREUM',
			'ASTRO',
		],
	},
];

