
// [GENERATED]
import { TokenPerChannel } from './types';

export const tokensPerChannel : Record<
  string,
  Record<string, TokenPerChannel>
> = {
  "2019": {
    "15": {
      "chainId": "2087",
      "destinationId": 15,
      "tokens": [
        "DOT",
        "PICA",
        "vDOT",
        "BNC_DOT",
        "ASTR",
        "lsDOT",
        "BLD",
        "IST"
      ]
    }
  },
  "2087": {
    "15": {
      "chainId": "2019",
      "destinationId": 15,
      "tokens": [
        "DOT",
        "PICA",
        "vDOT",
        "BNC_DOT",
        "ASTR",
        "lsDOT",
        "BLD",
        "IST"
      ]
    },
    "17": {
      "chainId": "centauri-1",
      "destinationId": 2,
      "tokens": [
        "PICA",
        "KSM",
        "DOT",
        "UMEE",
        "ASTR",
        "SDN",
        "USDT Kusama"
      ]
    }
  },
  "injective-1": {
    "145": {
      "chainId": "centauri-1",
      "destinationId": 29,
      "tokens": [
        "INJ"
      ]
    }
  },
  "celestia": {
    "12": {
      "chainId": "centauri-1",
      "destinationId": 38,
      "tokens": [
        "TIA"
      ]
    }
  },
  "ethereum": {
    "2": {
      "chainId": "centauri-1",
      "destinationId": 52,
      "tokens": [
        "PICA",
        "ETH",
        "DAI",
        "FXS",
        "sFRAX",
        "sfrxETH",
        "OSMO",
        "ENA",
        "FRAX",
        "frxETH",
        "wBTC",
        "pxETH",
        "PEPE",
        "CRV",
        "rETH",
        "crvUSD",
        "eETH",
        "USDe",
        "USDT Ethereum",
        "stETH",
        "ATOM",
        "IST",
        "stATOM",
        "BLD",
        "SEI",
        "SCRT",
        "STRD"
      ]
    }
  },
  "solana": {
    "1": {
      "chainId": "centauri-1",
      "destinationId": 71,
      "tokens": [
        "PICA",
        "OSMO",
        "SOL",
        "ETH",
        "wSOL",
        "WHINE",
        "LST",
        "bSOL",
        "JitoSOL",
        "edgeSOL",
        "hSOL",
        "jupSOL",
        "mSOL",
        "BONK",
        "WIF",
        "USDT Solana",
        "DAI",
        "USDT Ethereum",
        "CRV",
        "wBTC",
        "rETH",
        "crvUSD",
        "FRAX",
        "FXS",
        "frxETH",
        "sfrxETH",
        "sFRAX",
        "pxETH",
        "eETH",
        "ENA",
        "USDe",
        "PEPE",
        "ATOM",
        "stATOM",
        "IST",
        "SEI",
        "SCRT",
        "STARS",
        "BLD",
        "STRD",
        "SHD",
        "SILK",
        "DOT",
        "KSM",
        "XRP",
        "COREUM",
        "ASTRO"
      ]
    }
  },
  "archway-1": {
    "108": {
      "chainId": "centauri-1",
      "destinationId": 50,
      "tokens": [
        "PICA",
        "ETH",
        "DAI",
        "FXS",
        "sFRAX",
        "sfrxETH",
        "OSMO",
        "ENA",
        "FRAX",
        "frxETH",
        "wBTC",
        "pxETH",
        "PEPE",
        "CRV",
        "rETH",
        "crvUSD",
        "eETH",
        "USDe",
        "USDT Ethereum",
        "stETH",
        "ATOM",
        "IST",
        "stATOM",
        "BLD",
        "SEI",
        "SCRT",
        "STRD"
      ]
    }
  },
  "centauri-1": {
    "0": {
      "chainId": "chihuahua-1",
      "destinationId": 62,
      "tokens": [
        "UHUAHUA",
        "PICA"
      ]
    },
    "2": {
      "chainId": "2087",
      "destinationId": 17,
      "tokens": [
        "PICA",
        "KSM",
        "DOT",
        "UMEE",
        "ASTR",
        "SDN",
        "USDT Kusama"
      ]
    },
    "3": {
      "chainId": "osmosis-1",
      "destinationId": 1279,
      "tokens": [
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "stATOM",
        "SILK",
        "BNC_KSM",
        "vKSM",
        "BNC_DOT",
        "vDOT",
        "EQD",
        "USDT",
        "ASTR",
        "SDN",
        "EQ",
        "MOVR",
        "IST",
        "BLD",
        "TIA",
        "GLMR",
        "USDT",
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "STRD",
        "stATOM",
        "STARS",
        "NTRN",
        "CRE",
        "bCRE",
        "SCRT",
        "SILK",
        "TIA",
        "IST",
        "UMEE",
        "KUJI",
        "USK",
        "INJ",
        "QCK",
        "BLD",
        "MOVR",
        "vKSM",
        "vDOT",
        "SEI"
      ]
    },
    "4": {
      "chainId": "cosmoshub-4",
      "destinationId": 617,
      "tokens": [
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "stATOM",
        "SILK",
        "BNC_KSM",
        "vKSM",
        "BNC_DOT",
        "vDOT",
        "EQD",
        "USDT",
        "ASTR",
        "SDN",
        "EQ",
        "MOVR",
        "IST",
        "BLD",
        "TIA",
        "GLMR",
        "USDT",
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "STRD",
        "stATOM",
        "STARS",
        "NTRN",
        "CRE",
        "bCRE",
        "SCRT",
        "SILK",
        "TIA",
        "IST",
        "UMEE",
        "KUJI",
        "USK",
        "INJ",
        "QCK",
        "BLD",
        "MOVR",
        "vKSM",
        "vDOT",
        "SEI"
      ]
    },
    "5": {
      "chainId": "stride-1",
      "destinationId": 134,
      "tokens": [
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "stATOM",
        "SILK",
        "BNC_KSM",
        "vKSM",
        "BNC_DOT",
        "vDOT",
        "EQD",
        "USDT",
        "ASTR",
        "SDN",
        "EQ",
        "MOVR",
        "IST",
        "BLD",
        "TIA",
        "GLMR",
        "USDT",
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "STRD",
        "stATOM",
        "STARS",
        "NTRN",
        "CRE",
        "bCRE",
        "SCRT",
        "SILK",
        "TIA",
        "IST",
        "UMEE",
        "KUJI",
        "USK",
        "INJ",
        "QCK",
        "BLD",
        "MOVR",
        "vKSM",
        "vDOT",
        "SEI"
      ]
    },
    "6": {
      "chainId": "stargaze-1",
      "destinationId": 184,
      "tokens": [
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "stATOM",
        "SILK",
        "BNC_KSM",
        "vKSM",
        "BNC_DOT",
        "vDOT",
        "EQD",
        "USDT",
        "ASTR",
        "SDN",
        "EQ",
        "MOVR",
        "IST",
        "BLD",
        "TIA",
        "GLMR",
        "USDT",
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "STRD",
        "stATOM",
        "STARS",
        "NTRN",
        "CRE",
        "bCRE",
        "SCRT",
        "SILK",
        "TIA",
        "IST",
        "UMEE",
        "KUJI",
        "USK",
        "INJ",
        "QCK",
        "BLD",
        "MOVR",
        "vKSM",
        "vDOT",
        "SEI"
      ]
    },
    "9": {
      "chainId": "quicksilver-2",
      "destinationId": 94,
      "tokens": [
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "stATOM",
        "SILK",
        "BNC_KSM",
        "vKSM",
        "BNC_DOT",
        "vDOT",
        "EQD",
        "USDT",
        "ASTR",
        "SDN",
        "EQ",
        "MOVR",
        "IST",
        "BLD",
        "TIA",
        "GLMR",
        "USDT",
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "STRD",
        "stATOM",
        "STARS",
        "NTRN",
        "CRE",
        "bCRE",
        "SCRT",
        "SILK",
        "TIA",
        "IST",
        "UMEE",
        "KUJI",
        "USK",
        "INJ",
        "QCK",
        "BLD",
        "MOVR",
        "vKSM",
        "vDOT",
        "SEI"
      ]
    },
    "11": {
      "chainId": "crescent-1",
      "destinationId": 64,
      "tokens": [
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "stATOM",
        "SILK",
        "BNC_KSM",
        "vKSM",
        "BNC_DOT",
        "vDOT",
        "EQD",
        "USDT",
        "ASTR",
        "SDN",
        "EQ",
        "MOVR",
        "IST",
        "BLD",
        "TIA",
        "GLMR",
        "USDT",
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "STRD",
        "stATOM",
        "STARS",
        "NTRN",
        "CRE",
        "bCRE",
        "SCRT",
        "SILK",
        "TIA",
        "IST",
        "UMEE",
        "KUJI",
        "USK",
        "INJ",
        "QCK",
        "BLD",
        "MOVR",
        "vKSM",
        "vDOT",
        "SEI"
      ]
    },
    "13": {
      "chainId": "agoric-3",
      "destinationId": 55,
      "tokens": [
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "stATOM",
        "SILK",
        "BNC_KSM",
        "vKSM",
        "BNC_DOT",
        "vDOT",
        "EQD",
        "USDT",
        "ASTR",
        "SDN",
        "EQ",
        "MOVR",
        "IST",
        "BLD",
        "TIA",
        "GLMR",
        "USDT",
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "STRD",
        "stATOM",
        "STARS",
        "NTRN",
        "CRE",
        "bCRE",
        "SCRT",
        "SILK",
        "TIA",
        "IST",
        "UMEE",
        "KUJI",
        "USK",
        "INJ",
        "QCK",
        "BLD",
        "MOVR",
        "vKSM",
        "vDOT",
        "SEI"
      ]
    },
    "14": {
      "chainId": "secret-4",
      "destinationId": 80,
      "tokens": [
        "SCRT",
        "SILK",
        "SHD"
      ]
    },
    "18": {
      "chainId": "neutron-1",
      "destinationId": 17,
      "tokens": [
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "stATOM",
        "SILK",
        "BNC_KSM",
        "vKSM",
        "BNC_DOT",
        "vDOT",
        "EQD",
        "USDT",
        "ASTR",
        "SDN",
        "EQ",
        "MOVR",
        "IST",
        "BLD",
        "TIA",
        "GLMR",
        "USDT",
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "STRD",
        "stATOM",
        "STARS",
        "NTRN",
        "CRE",
        "bCRE",
        "SCRT",
        "SILK",
        "TIA",
        "IST",
        "UMEE",
        "KUJI",
        "USK",
        "INJ",
        "QCK",
        "BLD",
        "MOVR",
        "vKSM",
        "vDOT",
        "SEI"
      ]
    },
    "20": {
      "chainId": "umee-1",
      "destinationId": 99,
      "tokens": [
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "stATOM",
        "SILK",
        "BNC_KSM",
        "vKSM",
        "BNC_DOT",
        "vDOT",
        "EQD",
        "USDT",
        "ASTR",
        "SDN",
        "EQ",
        "MOVR",
        "IST",
        "BLD",
        "TIA",
        "GLMR",
        "USDT",
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "STRD",
        "stATOM",
        "STARS",
        "NTRN",
        "CRE",
        "bCRE",
        "SCRT",
        "SILK",
        "TIA",
        "IST",
        "UMEE",
        "KUJI",
        "USK",
        "INJ",
        "QCK",
        "BLD",
        "MOVR",
        "vKSM",
        "vDOT",
        "SEI"
      ]
    },
    "27": {
      "chainId": "kaiyo-1",
      "destinationId": 101,
      "tokens": [
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "stATOM",
        "SILK",
        "BNC_KSM",
        "vKSM",
        "BNC_DOT",
        "vDOT",
        "EQD",
        "USDT",
        "ASTR",
        "SDN",
        "EQ",
        "MOVR",
        "IST",
        "BLD",
        "TIA",
        "GLMR",
        "USDT",
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "STRD",
        "stATOM",
        "STARS",
        "NTRN",
        "CRE",
        "bCRE",
        "SCRT",
        "SILK",
        "TIA",
        "IST",
        "UMEE",
        "KUJI",
        "USK",
        "INJ",
        "QCK",
        "BLD",
        "MOVR",
        "vKSM",
        "vDOT",
        "SEI"
      ]
    },
    "29": {
      "chainId": "injective-1",
      "destinationId": 145,
      "tokens": [
        "INJ"
      ]
    },
    "38": {
      "chainId": "celestia",
      "destinationId": 12,
      "tokens": [
        "TIA"
      ]
    },
    "50": {
      "chainId": "archway-1",
      "destinationId": 108,
      "tokens": [
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "stATOM",
        "SILK",
        "BNC_KSM",
        "vKSM",
        "BNC_DOT",
        "vDOT",
        "EQD",
        "USDT",
        "ASTR",
        "SDN",
        "EQ",
        "MOVR",
        "IST",
        "BLD",
        "TIA",
        "GLMR",
        "USDT",
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "STRD",
        "stATOM",
        "STARS",
        "NTRN",
        "CRE",
        "bCRE",
        "SCRT",
        "SILK",
        "TIA",
        "IST",
        "UMEE",
        "KUJI",
        "USK",
        "INJ",
        "QCK",
        "BLD",
        "MOVR",
        "vKSM",
        "vDOT",
        "SEI"
      ]
    },
    "52": {
      "chainId": "ethereum",
      "destinationId": 2,
      "tokens": [
        "PICA",
        "ETH",
        "DAI",
        "FXS",
        "sFRAX",
        "sfrxETH",
        "OSMO",
        "ENA",
        "FRAX",
        "frxETH",
        "wBTC",
        "pxETH",
        "PEPE",
        "CRV",
        "rETH",
        "crvUSD",
        "eETH",
        "USDe",
        "USDT Ethereum",
        "stETH",
        "ATOM",
        "IST",
        "stATOM",
        "BLD",
        "SEI",
        "SCRT",
        "STRD"
      ]
    },
    "56": {
      "chainId": "coreum-mainnet-1",
      "destinationId": 31,
      "tokens": [
        "COREUM",
        "XRP"
      ]
    },
    "71": {
      "chainId": "solana",
      "destinationId": 1,
      "tokens": [
        "PICA",
        "OSMO",
        "SOL",
        "ETH",
        "wSOL",
        "WHINE",
        "LST",
        "bSOL",
        "JitoSOL",
        "edgeSOL",
        "hSOL",
        "jupSOL",
        "mSOL",
        "BONK",
        "WIF",
        "USDT Solana",
        "DAI",
        "USDT Ethereum",
        "CRV",
        "wBTC",
        "rETH",
        "crvUSD",
        "FRAX",
        "FXS",
        "frxETH",
        "sfrxETH",
        "sFRAX",
        "pxETH",
        "eETH",
        "ENA",
        "USDe",
        "PEPE",
        "ATOM",
        "stATOM",
        "IST",
        "SEI",
        "SCRT",
        "STARS",
        "BLD",
        "STRD",
        "SHD",
        "SILK",
        "DOT",
        "KSM",
        "XRP",
        "COREUM",
        "ASTRO"
      ]
    }
  },
  "chihuahua-1": {
    "62": {
      "chainId": "centauri-1",
      "destinationId": 0,
      "tokens": [
        "PICA",
        "ETH",
        "DAI",
        "FXS",
        "sFRAX",
        "sfrxETH",
        "OSMO",
        "ENA",
        "FRAX",
        "frxETH",
        "wBTC",
        "pxETH",
        "PEPE",
        "CRV",
        "rETH",
        "crvUSD",
        "eETH",
        "USDe",
        "USDT Ethereum",
        "stETH",
        "ATOM",
        "IST",
        "stATOM",
        "BLD",
        "SEI",
        "SCRT",
        "STRD"
      ]
    }
  },
  "coreum-mainnet-1": {
    "31": {
      "chainId": "centauri-1",
      "destinationId": 56,
      "tokens": [
        "PICA",
        "ETH",
        "DAI",
        "FXS",
        "sFRAX",
        "sfrxETH",
        "OSMO",
        "ENA",
        "FRAX",
        "frxETH",
        "wBTC",
        "pxETH",
        "PEPE",
        "CRV",
        "rETH",
        "crvUSD",
        "eETH",
        "USDe",
        "USDT Ethereum",
        "stETH",
        "ATOM",
        "IST",
        "stATOM",
        "BLD",
        "SEI",
        "SCRT",
        "STRD"
      ]
    }
  },
  "kaiyo-1": {
    "101": {
      "chainId": "centauri-1",
      "destinationId": 27,
      "tokens": [
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "stATOM",
        "SILK",
        "BNC_KSM",
        "vKSM",
        "BNC_DOT",
        "vDOT",
        "EQD",
        "USDT",
        "ASTR",
        "SDN",
        "EQ",
        "MOVR",
        "IST",
        "BLD",
        "TIA",
        "GLMR",
        "USDT",
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "STRD",
        "stATOM",
        "STARS",
        "NTRN",
        "CRE",
        "bCRE",
        "SCRT",
        "SILK",
        "TIA",
        "IST",
        "UMEE",
        "KUJI",
        "USK",
        "INJ",
        "QCK",
        "BLD",
        "MOVR",
        "vKSM",
        "vDOT",
        "SEI"
      ]
    }
  },
  "quicksilver-2": {
    "94": {
      "chainId": "centauri-1",
      "destinationId": 9,
      "tokens": [
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "stATOM",
        "SILK",
        "BNC_KSM",
        "vKSM",
        "BNC_DOT",
        "vDOT",
        "EQD",
        "USDT",
        "ASTR",
        "SDN",
        "EQ",
        "MOVR",
        "IST",
        "BLD",
        "TIA",
        "GLMR",
        "USDT",
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "STRD",
        "stATOM",
        "STARS",
        "NTRN",
        "CRE",
        "bCRE",
        "SCRT",
        "SILK",
        "TIA",
        "IST",
        "UMEE",
        "KUJI",
        "USK",
        "INJ",
        "QCK",
        "BLD",
        "MOVR",
        "vKSM",
        "vDOT",
        "SEI"
      ]
    }
  },
  "secret-4": {
    "80": {
      "chainId": "centauri-1",
      "destinationId": 14,
      "tokens": [
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "stATOM",
        "SILK",
        "BNC_KSM",
        "vKSM",
        "BNC_DOT",
        "vDOT",
        "EQD",
        "USDT",
        "ASTR",
        "SDN",
        "EQ",
        "MOVR",
        "IST",
        "BLD",
        "TIA",
        "GLMR",
        "USDT",
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "STRD",
        "stATOM",
        "STARS",
        "NTRN",
        "CRE",
        "bCRE",
        "SCRT",
        "SILK",
        "TIA",
        "IST",
        "UMEE",
        "KUJI",
        "USK",
        "INJ",
        "QCK",
        "BLD",
        "MOVR",
        "vKSM",
        "vDOT",
        "SEI"
      ]
    }
  },
  "pacific-1": {
    "0": {
      "chainId": "osmosis-1",
      "destinationId": 782,
      "tokens": [
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "stATOM",
        "SILK",
        "BNC_KSM",
        "vKSM",
        "BNC_DOT",
        "vDOT",
        "EQD",
        "USDT",
        "ASTR",
        "SDN",
        "EQ",
        "MOVR",
        "IST",
        "BLD",
        "TIA",
        "GLMR",
        "USDT",
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "STRD",
        "stATOM",
        "STARS",
        "NTRN",
        "CRE",
        "bCRE",
        "SCRT",
        "SILK",
        "TIA",
        "IST",
        "UMEE",
        "KUJI",
        "USK",
        "INJ",
        "QCK",
        "BLD",
        "MOVR",
        "vKSM",
        "vDOT",
        "SEI"
      ]
    }
  },
  "agoric-3": {
    "55": {
      "chainId": "centauri-1",
      "destinationId": 13,
      "tokens": [
        "PICA",
        "ETH",
        "DAI",
        "FXS",
        "sFRAX",
        "sfrxETH",
        "OSMO",
        "ENA",
        "FRAX",
        "frxETH",
        "wBTC",
        "pxETH",
        "PEPE",
        "CRV",
        "rETH",
        "crvUSD",
        "eETH",
        "USDe",
        "USDT Ethereum",
        "stETH",
        "ATOM",
        "IST",
        "stATOM",
        "BLD",
        "SEI",
        "SCRT",
        "STRD"
      ]
    }
  },
  "cosmoshub-4": {
    "617": {
      "chainId": "centauri-1",
      "destinationId": 4,
      "tokens": [
        "PICA",
        "ETH",
        "DAI",
        "FXS",
        "sFRAX",
        "sfrxETH",
        "OSMO",
        "ENA",
        "FRAX",
        "frxETH",
        "wBTC",
        "pxETH",
        "PEPE",
        "CRV",
        "rETH",
        "crvUSD",
        "eETH",
        "USDe",
        "USDT Ethereum",
        "stETH",
        "ATOM",
        "IST",
        "stATOM",
        "BLD",
        "SEI",
        "SCRT",
        "STRD"
      ]
    }
  },
  "crescent-1": {
    "64": {
      "chainId": "centauri-1",
      "destinationId": 11,
      "tokens": [
        "PICA",
        "ETH",
        "DAI",
        "FXS",
        "sFRAX",
        "sfrxETH",
        "OSMO",
        "ENA",
        "FRAX",
        "frxETH",
        "wBTC",
        "pxETH",
        "PEPE",
        "CRV",
        "rETH",
        "crvUSD",
        "eETH",
        "USDe",
        "USDT Ethereum",
        "stETH",
        "ATOM",
        "IST",
        "stATOM",
        "BLD",
        "SEI",
        "SCRT",
        "STRD"
      ]
    }
  },
  "neutron-1": {
    "17": {
      "chainId": "centauri-1",
      "destinationId": 18,
      "tokens": [
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "stATOM",
        "SILK",
        "BNC_KSM",
        "vKSM",
        "BNC_DOT",
        "vDOT",
        "EQD",
        "USDT",
        "ASTR",
        "SDN",
        "EQ",
        "MOVR",
        "IST",
        "BLD",
        "TIA",
        "GLMR",
        "USDT",
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "STRD",
        "stATOM",
        "STARS",
        "NTRN",
        "CRE",
        "bCRE",
        "SCRT",
        "SILK",
        "TIA",
        "IST",
        "UMEE",
        "KUJI",
        "USK",
        "INJ",
        "QCK",
        "BLD",
        "MOVR",
        "vKSM",
        "vDOT",
        "SEI"
      ]
    }
  },
  "osmosis-1": {
    "782": {
      "chainId": "pacific-1",
      "destinationId": 0,
      "tokens": [
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "stATOM",
        "SILK",
        "BNC_KSM",
        "vKSM",
        "BNC_DOT",
        "vDOT",
        "EQD",
        "USDT",
        "ASTR",
        "SDN",
        "EQ",
        "MOVR",
        "IST",
        "BLD",
        "TIA",
        "GLMR",
        "USDT",
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "STRD",
        "stATOM",
        "STARS",
        "NTRN",
        "CRE",
        "bCRE",
        "SCRT",
        "SILK",
        "TIA",
        "IST",
        "UMEE",
        "KUJI",
        "USK",
        "INJ",
        "QCK",
        "BLD",
        "MOVR",
        "vKSM",
        "vDOT",
        "SEI"
      ]
    },
    "1279": {
      "chainId": "centauri-1",
      "destinationId": 3,
      "tokens": [
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "stATOM",
        "SILK",
        "BNC_KSM",
        "vKSM",
        "BNC_DOT",
        "vDOT",
        "EQD",
        "USDT",
        "ASTR",
        "SDN",
        "EQ",
        "MOVR",
        "IST",
        "BLD",
        "TIA",
        "GLMR",
        "USDT",
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "STRD",
        "stATOM",
        "STARS",
        "NTRN",
        "CRE",
        "bCRE",
        "SCRT",
        "SILK",
        "TIA",
        "IST",
        "UMEE",
        "KUJI",
        "USK",
        "INJ",
        "QCK",
        "BLD",
        "MOVR",
        "vKSM",
        "vDOT",
        "SEI"
      ]
    }
  },
  "stargaze-1": {
    "184": {
      "chainId": "centauri-1",
      "destinationId": 6,
      "tokens": [
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "stATOM",
        "SILK",
        "BNC_KSM",
        "vKSM",
        "BNC_DOT",
        "vDOT",
        "EQD",
        "USDT",
        "ASTR",
        "SDN",
        "EQ",
        "MOVR",
        "IST",
        "BLD",
        "TIA",
        "GLMR",
        "USDT",
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "STRD",
        "stATOM",
        "STARS",
        "NTRN",
        "CRE",
        "bCRE",
        "SCRT",
        "SILK",
        "TIA",
        "IST",
        "UMEE",
        "KUJI",
        "USK",
        "INJ",
        "QCK",
        "BLD",
        "MOVR",
        "vKSM",
        "vDOT",
        "SEI"
      ]
    }
  },
  "stride-1": {
    "134": {
      "chainId": "centauri-1",
      "destinationId": 5,
      "tokens": [
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "stATOM",
        "SILK",
        "BNC_KSM",
        "vKSM",
        "BNC_DOT",
        "vDOT",
        "EQD",
        "USDT",
        "ASTR",
        "SDN",
        "EQ",
        "MOVR",
        "IST",
        "BLD",
        "TIA",
        "GLMR",
        "USDT",
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "STRD",
        "stATOM",
        "STARS",
        "NTRN",
        "CRE",
        "bCRE",
        "SCRT",
        "SILK",
        "TIA",
        "IST",
        "UMEE",
        "KUJI",
        "USK",
        "INJ",
        "QCK",
        "BLD",
        "MOVR",
        "vKSM",
        "vDOT",
        "SEI"
      ]
    }
  },
  "umee-1": {
    "99": {
      "chainId": "centauri-1",
      "destinationId": 20,
      "tokens": [
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "stATOM",
        "SILK",
        "BNC_KSM",
        "vKSM",
        "BNC_DOT",
        "vDOT",
        "EQD",
        "USDT",
        "ASTR",
        "SDN",
        "EQ",
        "MOVR",
        "IST",
        "BLD",
        "TIA",
        "GLMR",
        "USDT",
        "PICA",
        "KSM",
        "DOT",
        "ATOM",
        "OSMO",
        "STRD",
        "stATOM",
        "STARS",
        "NTRN",
        "CRE",
        "bCRE",
        "SCRT",
        "SILK",
        "TIA",
        "IST",
        "UMEE",
        "KUJI",
        "USK",
        "INJ",
        "QCK",
        "BLD",
        "MOVR",
        "vKSM",
        "vDOT",
        "SEI"
      ]
    }
  }
} ;

